name: ðŸ†™ Release file check

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install autopub and plugins
        run: pip install autopub==1.0.0-alpha.18 PyGithub httpx pdm

      - name: Check release
        run: autopub -p autopub_plugins.github.pr_comment -p autopub_plugins.github.release check
        id: check
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        if: steps.check.outcome == 'success'
        run: autopub -p autopub_plugins.github.pr_comment -p autopub_plugins.github.release prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: autopub -p pdm -p autopub_plugins.github.pr_comment -p autopub_plugins.github.release build
        if: steps.check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: autopub -p pdm -p autopub_plugins.github.pr_comment -p autopub_plugins.github.release publish
        if: steps.check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
